### ISSUE TITLE
not giving error on wrong domain

### ISSUE THREAD

**Issue by zainbinfurqan** [ashokjayaprakash/email-domain-validator#2]
EmailDomainValidator.validate("test@test.com")
            .then(function (data) {
                console.log("Success ", data);
            })
            .catch(function (err) {
                console.log("ERR: ", err);
            });

Success  { isValidDomain: true, erorrMessage: [], invalidEmailList: [] }

**Comment by ashokjayaprakash** [comment]
@zainbinfurqan : [test.com](https://www.test.com/) is a valid domain name.

**Comment by zainbinfurqan** [comment]
//Valid Domain Response Object
	{ 
		isValidDomain: false,
		erorrMessage: [ 'test@test.com - queryMx ENODATA test.com'],
		invalidEmailList: [ 'test@test.com'] 
	};
if its correct then please update it
